import 'dotenv/config';
import express from "express";
import cors from "cors";
import OpenAI from "openai";
import PDFDocument from "pdfkit";
import multer from "multer";
import pdfParse from "pdf-parse-fixed";

const app = express();
const upload = multer();

// 1. UNIVERSAL PERMISSION (Bypasses all CORS blocks)
app.use(cors({ origin: "*" }));
app.use(express.json({ limit: "10mb" }));

// 2. INITIALIZE OPENAI
const client = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

// 3. AI BRAIN (Handles Resume Summary & Cover Letter Text)
app.post("/api/ai/generate", async (req, res) => {
  try {
    const { mode, text, payload } = req.body;
    let systemPrompt = "You are a professional career coach for the skilled trades (plumbing, electrical, construction, etc.).";
    let userPrompt = "";

    if (mode === "summary") {
      userPrompt = `Rewrite this raw resume text into a professional 5-7 sentence summary. Focus on trade skills and reliability. Do not use first-person pronouns (I, me, my). \n\nText: ${text}`;
    } else if (mode === "cover-letter") {
      userPrompt = `Write a professional cover letter for ${payload.applicantName} applying for ${payload.jobTitle} at ${payload.companyName}. \n\nExperience to highlight: ${payload.experience}`;
    }

    const completion = await client.chat.completions.create({
      model: "gpt-4o",
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userPrompt }
      ],
      temperature: 0.7,
    });

    const result = completion.choices[0]?.message?.content?.trim() || "";
    res.json({ result });
  } catch (err) {
    console.error("AI Generation Error:", err);
    res.status(500).json({ error: "AI failed to process. Check API Key." });
  }
});

// 4. RESUME UPLOAD BRAIN (Extracts text from PDF)
app.post("/api/ai/extract-summary", upload.single("file"), async (req, res) => {
  try {
    if (!req.file) return res.status(400).json({ error: "No file uploaded" });

    const pdfData = await pdfParse(req.file.buffer);
    const text = pdfData.text;

    const completion = await client.chat.completions.create({
      model: "gpt-4o",
      messages: [
        { role: "system", content: "You are a resume data extractor. Summarize the user's work history into 5 sentences." },
        { role: "user", content: text }
      ],
    });

    res.json({ summary: completion.choices[0].message.content });
  } catch (err) {
    console.error("Extraction Error:", err);
    res.status(500).json({ error: "Failed to read PDF." });
  }
});

// 5. PDF BRAIN (Generates the final PDF with the blue header)
app.post("/api/export/pdf", async (req, res) => {
  try {
    const data = req.body;
    const doc = new PDFDocument({ size: "LETTER", margin: 50 });

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename=TradePro-${data.applicantName || 'Document'}.pdf`);
    doc.pipe(res);

    // --- BLUE HEADER DESIGN ---
    doc.rect(0, 0, doc.page.width, 140).fill("#1F4E79");
    doc.fillColor("white");
    doc.font("Helvetica-Bold").fontSize(26).text(data.applicantName || "Trade Professional", 50, 45);
    doc.font("Helvetica").fontSize(11).text(`${data.applicantEmail} | ${data.applicantPhone}`, 50, 80);
    if (data.applicantCityStateZip) doc.text(data.applicantCityStateZip, 50, 95);

    // --- BODY CONTENT ---
    doc.fillColor("black").moveDown(8);
    doc.font("Helvetica").fontSize(12).text(data.letter || data.summary || "Content missing.", {
      width: 512,
      align: "left",
      lineGap: 4
    });

    // --- FOOTER ---
    doc.fontSize(10).fillColor("grey").text("Generated by TradeProTech.ai", 0, doc.page.height - 50, { align: "center" });

    doc.end();
  } catch (err) {
    console.error("PDF Export Error:", err);
    res.status(500).send("Failed to create PDF.");
  }
});

app.get("/", (req, res) => res.send("TradePro Master Brain is Live"));

const PORT = process.env.PORT || 3001;
app.listen(PORT, "0.0.0.0", () => {
  console.log(`🚀 Master Brain listening on port ${PORT}`);
});
